// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEBgJtYwB3uOEiVbr-P0dbE3Y0nWYpDdU',
    appId: '1:270925815940:web:9400bddfdd84cc665622d1',
    messagingSenderId: '270925815940',
    projectId: 'flutter-firebase-5ce77',
    authDomain: 'flutter-firebase-5ce77.firebaseapp.com',
    storageBucket: 'flutter-firebase-5ce77.firebasestorage.app',
    measurementId: 'G-4FMWG7ZRZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCe_aNCpNZJyb8sy7H7oRIfUL_k0U1Jjg',
    appId: '1:270925815940:android:88b7c9931878798a5622d1',
    messagingSenderId: '270925815940',
    projectId: 'flutter-firebase-5ce77',
    storageBucket: 'flutter-firebase-5ce77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJyzn441nLCOa4nkSjPin6B0sgVDiAHoE',
    appId: '1:270925815940:ios:bcbc4f7c48a9a8f45622d1',
    messagingSenderId: '270925815940',
    projectId: 'flutter-firebase-5ce77',
    storageBucket: 'flutter-firebase-5ce77.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJyzn441nLCOa4nkSjPin6B0sgVDiAHoE',
    appId: '1:270925815940:ios:bcbc4f7c48a9a8f45622d1',
    messagingSenderId: '270925815940',
    projectId: 'flutter-firebase-5ce77',
    storageBucket: 'flutter-firebase-5ce77.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEBgJtYwB3uOEiVbr-P0dbE3Y0nWYpDdU',
    appId: '1:270925815940:web:4f7189f5a36ffe025622d1',
    messagingSenderId: '270925815940',
    projectId: 'flutter-firebase-5ce77',
    authDomain: 'flutter-firebase-5ce77.firebaseapp.com',
    storageBucket: 'flutter-firebase-5ce77.firebasestorage.app',
    measurementId: 'G-1VZ4S61V0B',
  );
}
